name: Output
on:
    pull_request:
        types: opened
    workflow_dispatch:
    push:
      branches:
        - main 
        - activity-type
      paths-ignore:
        - .github/workflows/*

jobs:
    output: 
        runs-on: ubuntu-latest
        steps:
            - name: Echo output
              run: echo " ${{ toJson(github.event) }}"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploy"